// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxFr-N032PQYjw_UbCUtbUdrUz2GcJlGA',
    appId: '1:1032334118158:web:e51da1bb324891efb65b5f',
    messagingSenderId: '1032334118158',
    projectId: 'mealfinder-adbe6',
    authDomain: 'mealfinder-adbe6.firebaseapp.com',
    databaseURL: 'https://mealfinder-adbe6-default-rtdb.firebaseio.com',
    storageBucket: 'mealfinder-adbe6.appspot.com',
    measurementId: 'G-7QZ27F6K3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAloI3A5uA7mObM3u0j6eYrb_jEc1-NGfY',
    appId: '1:1032334118158:android:c67aba443b2ae866b65b5f',
    messagingSenderId: '1032334118158',
    projectId: 'mealfinder-adbe6',
    databaseURL: 'https://mealfinder-adbe6-default-rtdb.firebaseio.com',
    storageBucket: 'mealfinder-adbe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvxugxvyIE6gMAJEZYN9lBh9-BkysbXF4',
    appId: '1:1032334118158:ios:935f03547078a8f3b65b5f',
    messagingSenderId: '1032334118158',
    projectId: 'mealfinder-adbe6',
    databaseURL: 'https://mealfinder-adbe6-default-rtdb.firebaseio.com',
    storageBucket: 'mealfinder-adbe6.appspot.com',
    iosBundleId: 'com.example.mealFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvxugxvyIE6gMAJEZYN9lBh9-BkysbXF4',
    appId: '1:1032334118158:ios:bf76be11f28ac3d2b65b5f',
    messagingSenderId: '1032334118158',
    projectId: 'mealfinder-adbe6',
    databaseURL: 'https://mealfinder-adbe6-default-rtdb.firebaseio.com',
    storageBucket: 'mealfinder-adbe6.appspot.com',
    iosBundleId: 'com.example.mealFinder.RunnerTests',
  );
}
